version: '2'
networks:
  default:
    external:
      name: ws_bridge

services:
  web:
    build: .
    command: python app.py
    ports:
      - "5009:5009"
    volumes:
      - .:/code
    container_name: usr
