version: '2'
services:
 base:
  build: .
  command: python app.py
  ports:
   - 80:5000
  volumes:
   - .:/code
  networks:
    - ws_bridge
 usr:
  build: .
  command: python WebServices/Pirmas/app.py
  ports:
    - "5009:5009"
  volumes:
    - .:/code
  networks:
    - ws_bridge

networks:
  ws_bridge:
